from model import Dish, PartOfTheDayEnum


# взято отсюда https://health-diet.ru/table_calorie/?utm_source=leftMenu&utm_medium=table_calorie

dishes = [
    Dish(
        name='Яичница с курицей и грибами',
        calories=210.4,
        carbs=3.4,
        fats=18.1,
        proteins=8.6,
        part_of_the_day=PartOfTheDayEnum.breakfast,
    ),
    Dish(
        name='Блинчики с морковью',
        calories=105.4,
        carbs=11,
        fats=5.3,
        proteins=4.2,
        part_of_the_day=PartOfTheDayEnum.breakfast,
    ),
    Dish(
        name='Горячий бутерброд',
        calories=301.6,
        carbs=8.8,
        fats=26.4,
        proteins=7.7,
        part_of_the_day=PartOfTheDayEnum.breakfast,
    ),
    Dish(
        name='Бурятский чай',
        calories=94,
        carbs=2.1,
        fats=9.3,
        proteins=0.7,
        part_of_the_day=PartOfTheDayEnum.breakfast,
    ),
    Dish(
        name='Бефстроганов',
        calories=355.4,
        carbs=5.7,
        fats=27.4,
        proteins=21.4,
        part_of_the_day=PartOfTheDayEnum.dinner,
    ),
    Dish(
        name='Рагу из овощей',
        calories=147.2,
        carbs=15.4,
        fats=3,
        proteins=1.2,
        part_of_the_day=PartOfTheDayEnum.dinner,
    ),
    Dish(
        name='Рыбный салат',
        calories=207,
        carbs=4.5,
        fats=18.3,
        proteins=5.1,
        part_of_the_day=PartOfTheDayEnum.dinner,
    ),
    Dish(
        name='Картофельное пюре',
        calories=81.7,
        carbs=8.5,
        fats=4.6,
        proteins=2.1,
        part_of_the_day=PartOfTheDayEnum.dinner,
    ),
    Dish(
        name='Гречневая каша рассыпчатая',
        calories=98.7,
        carbs=17.1,
        fats=2.2,
        proteins=3.6,
        part_of_the_day=PartOfTheDayEnum.dinner,
    ),
    Dish(
        name='Кисель брусничный',
        calories=75.2,
        carbs=19.9,
        fats=0.1,
        proteins=0.1,
        part_of_the_day=PartOfTheDayEnum.dinner,
    ),
    Dish(
        name='Апельсин',
        calories=43,
        carbs=8.1,
        fats=0.2,
        proteins=0.9,
        part_of_the_day=PartOfTheDayEnum.lunch,
    ),
    Dish(
        name='Пирог яблочный открытый',
        calories=193.6,
        carbs=32,
        fats=7.3,
        proteins=2.1,
        part_of_the_day=PartOfTheDayEnum.lunch,
    ),
    Dish(
        name='Соленые огурцы',
        calories=11.2,
        carbs=2.2,
        fats=0.1,
        proteins=0.6,
        part_of_the_day=PartOfTheDayEnum.lunch,
    ),
    Dish(
        name='Квас яблочный',
        calories=36.7,
        carbs=9.4,
        fats=0.1,
        proteins=0.2,
        part_of_the_day=PartOfTheDayEnum.lunch,
    ),
    Dish(
        name='Борщ',
        calories=57.7,
        carbs=4.3,
        fats=2.9,
        proteins=3.8,
        part_of_the_day=PartOfTheDayEnum.supper,
    ),
    Dish(
        name='Уха ростовская',
        calories=70.1,
        carbs=4.4,
        fats=2.2,
        proteins=8.5,
        part_of_the_day=PartOfTheDayEnum.supper,
    ),
    Dish(
        name='Творожная запеканка',
        calories=239.6,
        carbs=38.6,
        fats=6.8,
        proteins=8.4,
        part_of_the_day=PartOfTheDayEnum.supper,
    ),
    Dish(
        name='Облепиховое варенье',
        calories=164.6,
        carbs=34.4,
        fats=3.7,
        proteins=0.7,
        part_of_the_day=PartOfTheDayEnum.supper,
    ),
    Dish(
        name='Грибы в сметанном соусе',
        calories=204.2,
        carbs=3.8,
        fats=18.9,
        proteins=5,
        part_of_the_day=PartOfTheDayEnum.supper,
    ),
    Dish(
        name='Морс брусничный',
        calories=41.4,
        carbs=10.9,
        fats=0,
        proteins=0.1,
        part_of_the_day=PartOfTheDayEnum.supper,
    ),
    Dish(
        name='Окрошка',
        calories=75.7,
        carbs=4,
        fats=5.1,
        proteins=3.7,
        part_of_the_day=PartOfTheDayEnum.supper,
    ),
]
